#!/usr/bin/env python3
# votrax_dump_to_vhdl.py
#
# Converts votrax_input.txt (from MAME VOTRAX_DUMP) to a VHDL package
# containing input stimulus vectors for GHDL simulation.
#
# Usage:
#   python3 votrax_dump_to_vhdl.py votrax_input.txt > votrax_tb_vectors.vhd
#
# The generated package contains:
#   - A constant INPUT_VECTORS array with all events
#   - Each event has: ts_us (integer), event type, data
#
# Event types:
#   0 = RESET
#   1 = CLOCK  (data = freq in Hz)
#   2 = PHONE  (data(7:0) = phone, data(9:8) = inflection)
#   3 = INFLECTION (data = inflection value 0..3)

import sys
import re

EVENT_RESET      = 0
EVENT_CLOCK      = 1
EVENT_PHONE      = 2
EVENT_INFLECTION = 3

EVENT_NAMES = {
    EVENT_RESET:      "RESET",
    EVENT_CLOCK:      "CLOCK",
    EVENT_PHONE:      "PHONE",
    EVENT_INFLECTION: "INFLECTION",
}

def parse_kv(line):
    """Parse a line of key=value pairs into a dict."""
    result = {}
    for m in re.finditer(r'(\w+)=(\S+)', line):
        result[m.group(1)] = m.group(2)
    return result

def parse_input(filename):
    events = []
    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            kv = parse_kv(line)
            if 'event' not in kv:
                continue

            ts_ms = float(kv.get('ts', '0'))
            ts_us = int(round(ts_ms * 1000))
            ev    = kv['event']

            if ev == 'RESET':
                events.append((ts_us, EVENT_RESET, 0))

            elif ev == 'CLOCK':
                freq = int(kv['freq'])
                events.append((ts_us, EVENT_CLOCK, freq))

            elif ev == 'PHONE':
                phone      = int(kv['phone'], 16) & 0x3f
                inflection = int(kv.get('inflection', '0')) & 0x3
                # Pack: inflection in bits 7:6, phone in bits 5:0
                data = (inflection << 6) | phone
                events.append((ts_us, EVENT_PHONE, data))

            elif ev == 'INFLECTION':
                inflection = int(kv['inflection']) & 0x3
                events.append((ts_us, EVENT_INFLECTION, inflection))

    return events


def compress_gaps(events, max_gap_ms=500):
    """
    Compress long silent gaps between events.
    Gaps longer than max_gap_ms are clamped to max_gap_ms.
    Timestamps are rebased so the sequence stays tight.
    """
    if not events:
        return events

    max_gap_us = int(max_gap_ms * 1000)
    result = []
    offset = 0
    prev_orig_ts = events[0][0]

    for ts_us, ev, data in events:
        gap = ts_us - prev_orig_ts
        if gap > max_gap_us:
            offset += gap - max_gap_us
        prev_orig_ts = ts_us
        result.append((ts_us - offset, ev, data))

    return result

def write_vhdl(events, out=sys.stdout):
    w = out.write

    w("-- Auto-generated by votrax_dump_to_vhdl.py\n")
    w("-- Votrax SC01A testbench input vectors\n")
    w("-- DO NOT EDIT - regenerate from votrax_input.txt\n")
    w("\n")
    w("library ieee;\n")
    w("use ieee.std_logic_1164.all;\n")
    w("use ieee.numeric_std.all;\n")
    w("\n")
    w("package votrax_tb_vectors is\n")
    w("\n")
    w("    -- Event types\n")
    w("    constant EV_RESET      : integer := 0;\n")
    w("    constant EV_CLOCK      : integer := 1;\n")
    w("    constant EV_PHONE      : integer := 2;  -- data(5:0)=phone, data(7:6)=inflection\n")
    w("    constant EV_INFLECTION : integer := 3;  -- data(1:0)=inflection\n")
    w("\n")
    w("    type input_event_t is record\n")
    w("        ts_us  : integer;  -- timestamp in microseconds\n")
    w("        event  : integer;  -- event type (EV_*)\n")
    w("        data   : integer;  -- event data\n")
    w("    end record;\n")
    w("\n")
    w(f"    constant N_EVENTS : integer := {len(events)};\n")
    w("\n")
    w("    type input_vec_array is array(0 to N_EVENTS-1) of input_event_t;\n")
    w("\n")
    w("    constant INPUT_VECTORS : input_vec_array := (\n")

    for i, (ts_us, ev, data) in enumerate(events):
        comma = "," if i < len(events) - 1 else " "
        comment = f"-- {EVENT_NAMES[ev]}"
        if ev == EVENT_CLOCK:
            comment += f" freq={data}Hz"
        elif ev == EVENT_PHONE:
            phone      = data & 0x3f
            inflection = (data >> 6) & 0x3
            comment += f" phone=0x{phone:02X} inflection={inflection}"
        elif ev == EVENT_INFLECTION:
            comment += f" inflection={data}"

        w(f"        (ts_us=>{ts_us:10d}, event=>{ev}, data=>{data:10d}){comma}  {comment}\n")

    w("    );\n")
    w("\n")
    w("end package votrax_tb_vectors;\n")

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Convert Votrax dump to VHDL testbench vectors')
    parser.add_argument('input', help='votrax_input.txt from MAME dump')
    parser.add_argument('--max-gap', type=float, default=None,
                        help='Maximum gap between events in ms (default: no compression)')
    parser.add_argument('-o', '--output', default=None,
                        help='Output file (default: stdout)')
    args = parser.parse_args()

    events = parse_input(args.input)
    print(f"Parsed {len(events)} events, total duration: {events[-1][0]/1000:.1f}ms", file=sys.stderr)

    if args.max_gap is not None:
        events = compress_gaps(events, max_gap_ms=args.max_gap)
        print(f"After gap compression ({args.max_gap}ms max): total duration: {events[-1][0]/1000:.1f}ms", file=sys.stderr)

    if args.output:
        with open(args.output, 'w') as f:
            write_vhdl(events, out=f)
    else:
        write_vhdl(events)

# Patch: add compress_gaps function and update main
