-- f1_rom.vhd
-- Votrax SC01-A: First Formant (F1) Filter Coefficient ROM
--
-- Copyright (c) 2026 shufps
-- https://github.com/shufps/votrax-sc01a-vhdl
--
-- BSD 3-Clause License
--
-- Based on votrax.cpp (MAME), Copyright (c) Olivier Galibert
-- Auto-generated by gen_votrax_roms.cpp
--
-- 16 frequency steps × 8 coeffs = 128 entries, s(2.15) 18-bit
-- addr[6:3] = frequency index (0..15)
-- addr[2:0] = coeff index: 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f1_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(6 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f1_rom is

    type rom_t is array(0 to 127) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(     30, 18),  -- [   1] a0 = +0.000916
        to_signed(     43, 18),  -- [   2] a1 = +0.001312
        to_signed(     -5, 18),  -- [   3] a2 = -0.000153
        to_signed(    -18, 18),  -- [   4] a3 = -0.000549
        to_signed( -32445, 18),  -- [   5] b1 = -0.990143
        to_signed( -32743, 18),  -- [   6] b2 = -0.999237
        to_signed(  32471, 18),  -- [   7] b3 = +0.990936
        to_signed(  32768, 18),  -- [   8] b0 = +1.000000
        to_signed(     65, 18),  -- [   9] a0 = +0.001984
        to_signed(     91, 18),  -- [  10] a1 = +0.002777
        to_signed(    -11, 18),  -- [  11] a2 = -0.000336
        to_signed(    -38, 18),  -- [  12] a3 = -0.001160
        to_signed( -32417, 18),  -- [  13] b1 = -0.989288
        to_signed( -32714, 18),  -- [  14] b2 = -0.998352
        to_signed(  32471, 18),  -- [  15] b3 = +0.990936
        to_signed(  32768, 18),  -- [  16] b0 = +1.000000
        to_signed(     97, 18),  -- [  17] a0 = +0.002960
        to_signed(    137, 18),  -- [  18] a1 = +0.004181
        to_signed(    -16, 18),  -- [  19] a2 = -0.000488
        to_signed(    -57, 18),  -- [  20] a3 = -0.001740
        to_signed( -32390, 18),  -- [  21] b1 = -0.988464
        to_signed( -32687, 18),  -- [  22] b2 = -0.997528
        to_signed(  32471, 18),  -- [  23] b3 = +0.990936
        to_signed(  32768, 18),  -- [  24] b0 = +1.000000
        to_signed(    131, 18),  -- [  25] a0 = +0.003998
        to_signed(    185, 18),  -- [  26] a1 = +0.005646
        to_signed(    -22, 18),  -- [  27] a2 = -0.000671
        to_signed(    -77, 18),  -- [  28] a3 = -0.002350
        to_signed( -32362, 18),  -- [  29] b1 = -0.987610
        to_signed( -32659, 18),  -- [  30] b2 = -0.996674
        to_signed(  32471, 18),  -- [  31] b3 = +0.990936
        to_signed(  32768, 18),  -- [  32] b0 = +1.000000
        to_signed(    162, 18),  -- [  33] a0 = +0.004944
        to_signed(    230, 18),  -- [  34] a1 = +0.007019
        to_signed(    -27, 18),  -- [  35] a2 = -0.000824
        to_signed(    -95, 18),  -- [  36] a3 = -0.002899
        to_signed( -32336, 18),  -- [  37] b1 = -0.986816
        to_signed( -32633, 18),  -- [  38] b2 = -0.995880
        to_signed(  32471, 18),  -- [  39] b3 = +0.990936
        to_signed(  32768, 18),  -- [  40] b0 = +1.000000
        to_signed(    196, 18),  -- [  41] a0 = +0.005981
        to_signed(    278, 18),  -- [  42] a1 = +0.008484
        to_signed(    -33, 18),  -- [  43] a2 = -0.001007
        to_signed(   -115, 18),  -- [  44] a3 = -0.003510
        to_signed( -32308, 18),  -- [  45] b1 = -0.985962
        to_signed( -32605, 18),  -- [  46] b2 = -0.995026
        to_signed(  32471, 18),  -- [  47] b3 = +0.990936
        to_signed(  32768, 18),  -- [  48] b0 = +1.000000
        to_signed(    229, 18),  -- [  49] a0 = +0.006989
        to_signed(    323, 18),  -- [  50] a1 = +0.009857
        to_signed(    -39, 18),  -- [  51] a2 = -0.001190
        to_signed(   -134, 18),  -- [  52] a3 = -0.004089
        to_signed( -32281, 18),  -- [  53] b1 = -0.985138
        to_signed( -32578, 18),  -- [  54] b2 = -0.994202
        to_signed(  32471, 18),  -- [  55] b3 = +0.990936
        to_signed(  32768, 18),  -- [  56] b0 = +1.000000
        to_signed(    262, 18),  -- [  57] a0 = +0.007996
        to_signed(    372, 18),  -- [  58] a1 = +0.011353
        to_signed(    -44, 18),  -- [  59] a2 = -0.001343
        to_signed(   -153, 18),  -- [  60] a3 = -0.004669
        to_signed( -32253, 18),  -- [  61] b1 = -0.984283
        to_signed( -32550, 18),  -- [  62] b2 = -0.993347
        to_signed(  32471, 18),  -- [  63] b3 = +0.990936
        to_signed(  32768, 18),  -- [  64] b0 = +1.000000
        to_signed(    294, 18),  -- [  65] a0 = +0.008972
        to_signed(    416, 18),  -- [  66] a1 = +0.012695
        to_signed(    -50, 18),  -- [  67] a2 = -0.001526
        to_signed(   -172, 18),  -- [  68] a3 = -0.005249
        to_signed( -32227, 18),  -- [  69] b1 = -0.983490
        to_signed( -32524, 18),  -- [  70] b2 = -0.992554
        to_signed(  32471, 18),  -- [  71] b3 = +0.990936
        to_signed(  32768, 18),  -- [  72] b0 = +1.000000
        to_signed(    328, 18),  -- [  73] a0 = +0.010010
        to_signed(    464, 18),  -- [  74] a1 = +0.014160
        to_signed(    -55, 18),  -- [  75] a2 = -0.001678
        to_signed(   -191, 18),  -- [  76] a3 = -0.005829
        to_signed( -32199, 18),  -- [  77] b1 = -0.982635
        to_signed( -32496, 18),  -- [  78] b2 = -0.991699
        to_signed(  32471, 18),  -- [  79] b3 = +0.990936
        to_signed(  32768, 18),  -- [  80] b0 = +1.000000
        to_signed(    360, 18),  -- [  81] a0 = +0.010986
        to_signed(    509, 18),  -- [  82] a1 = +0.015533
        to_signed(    -61, 18),  -- [  83] a2 = -0.001862
        to_signed(   -210, 18),  -- [  84] a3 = -0.006409
        to_signed( -32172, 18),  -- [  85] b1 = -0.981812
        to_signed( -32469, 18),  -- [  86] b2 = -0.990875
        to_signed(  32471, 18),  -- [  87] b3 = +0.990936
        to_signed(  32768, 18),  -- [  88] b0 = +1.000000
        to_signed(    394, 18),  -- [  89] a0 = +0.012024
        to_signed(    557, 18),  -- [  90] a1 = +0.016998
        to_signed(    -67, 18),  -- [  91] a2 = -0.002045
        to_signed(   -230, 18),  -- [  92] a3 = -0.007019
        to_signed( -32144, 18),  -- [  93] b1 = -0.980957
        to_signed( -32441, 18),  -- [  94] b2 = -0.990021
        to_signed(  32471, 18),  -- [  95] b3 = +0.990936
        to_signed(  32768, 18),  -- [  96] b0 = +1.000000
        to_signed(    425, 18),  -- [  97] a0 = +0.012970
        to_signed(    602, 18),  -- [  98] a1 = +0.018372
        to_signed(    -72, 18),  -- [  99] a2 = -0.002197
        to_signed(   -248, 18),  -- [ 100] a3 = -0.007568
        to_signed( -32118, 18),  -- [ 101] b1 = -0.980164
        to_signed( -32415, 18),  -- [ 102] b2 = -0.989227
        to_signed(  32472, 18),  -- [ 103] b3 = +0.990967
        to_signed(  32768, 18),  -- [ 104] b0 = +1.000000
        to_signed(    459, 18),  -- [ 105] a0 = +0.014008
        to_signed(    649, 18),  -- [ 106] a1 = +0.019806
        to_signed(    -78, 18),  -- [ 107] a2 = -0.002380
        to_signed(   -268, 18),  -- [ 108] a3 = -0.008179
        to_signed( -32090, 18),  -- [ 109] b1 = -0.979309
        to_signed( -32387, 18),  -- [ 110] b2 = -0.988373
        to_signed(  32472, 18),  -- [ 111] b3 = +0.990967
        to_signed(  32768, 18),  -- [ 112] b0 = +1.000000
        to_signed(    491, 18),  -- [ 113] a0 = +0.014984
        to_signed(    695, 18),  -- [ 114] a1 = +0.021210
        to_signed(    -83, 18),  -- [ 115] a2 = -0.002533
        to_signed(   -287, 18),  -- [ 116] a3 = -0.008759
        to_signed( -32064, 18),  -- [ 117] b1 = -0.978516
        to_signed( -32360, 18),  -- [ 118] b2 = -0.987549
        to_signed(  32472, 18),  -- [ 119] b3 = +0.990967
        to_signed(  32768, 18),  -- [ 120] b0 = +1.000000
        to_signed(    525, 18),  -- [ 121] a0 = +0.016022
        to_signed(    743, 18),  -- [ 122] a1 = +0.022675
        to_signed(    -89, 18),  -- [ 123] a2 = -0.002716
        to_signed(   -307, 18),  -- [ 124] a3 = -0.009369
        to_signed( -32036, 18),  -- [ 125] b1 = -0.977661
        to_signed( -32332, 18),  -- [ 126] b2 = -0.986694
        to_signed(  32472, 18)   -- [ 127] b3 = +0.990967
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;