-- f3_rom.vhd
-- Votrax SC01-A: Third Formant (F3) Filter Coefficient ROM
--
-- Copyright (c) 2026 shufps
-- https://github.com/shufps/votrax-sc01a-vhdl
--
-- BSD 3-Clause License
--
-- Based on votrax.cpp (MAME), Copyright (c) Olivier Galibert
-- Auto-generated by gen_votrax_roms.cpp
--
-- 16 frequency steps × 8 coeffs = 128 entries, s(2.15) 18-bit
-- addr[6:3] = frequency index (0..15)
-- addr[2:0] = coeff index: 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f3_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(6 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f3_rom is

    type rom_t is array(0 to 127) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(    318, 18),  -- [   1] a0 = +0.009705
        to_signed(    953, 18),  -- [   2] a1 = +0.029083
        to_signed(    953, 18),  -- [   3] a2 = +0.029083
        to_signed(    318, 18),  -- [   4] a3 = +0.009705
        to_signed( -30758, 18),  -- [   5] b1 = -0.938660
        to_signed( -31497, 18),  -- [   6] b2 = -0.961212
        to_signed(  32029, 18),  -- [   7] b3 = +0.977448
        to_signed(  32768, 18),  -- [   8] b0 = +1.000000
        to_signed(    400, 18),  -- [   9] a0 = +0.012207
        to_signed(   1200, 18),  -- [  10] a1 = +0.036621
        to_signed(   1200, 18),  -- [  11] a2 = +0.036621
        to_signed(    400, 18),  -- [  12] a3 = +0.012207
        to_signed( -30430, 18),  -- [  13] b1 = -0.928650
        to_signed( -31168, 18),  -- [  14] b2 = -0.951172
        to_signed(  32030, 18),  -- [  15] b3 = +0.977478
        to_signed(  32768, 18),  -- [  16] b0 = +1.000000
        to_signed(    483, 18),  -- [  17] a0 = +0.014740
        to_signed(   1450, 18),  -- [  18] a1 = +0.044250
        to_signed(   1450, 18),  -- [  19] a2 = +0.044250
        to_signed(    483, 18),  -- [  20] a3 = +0.014740
        to_signed( -30100, 18),  -- [  21] b1 = -0.918579
        to_signed( -30835, 18),  -- [  22] b2 = -0.941010
        to_signed(  32032, 18),  -- [  23] b3 = +0.977539
        to_signed(  32768, 18),  -- [  24] b0 = +1.000000
        to_signed(    565, 18),  -- [  25] a0 = +0.017242
        to_signed(   1694, 18),  -- [  26] a1 = +0.051697
        to_signed(   1694, 18),  -- [  27] a2 = +0.051697
        to_signed(    565, 18),  -- [  28] a3 = +0.017242
        to_signed( -29775, 18),  -- [  29] b1 = -0.908661
        to_signed( -30509, 18),  -- [  30] b2 = -0.931061
        to_signed(  32034, 18),  -- [  31] b3 = +0.977600
        to_signed(  32768, 18),  -- [  32] b0 = +1.000000
        to_signed(    650, 18),  -- [  33] a0 = +0.019836
        to_signed(   1950, 18),  -- [  34] a1 = +0.059509
        to_signed(   1950, 18),  -- [  35] a2 = +0.059509
        to_signed(    650, 18),  -- [  36] a3 = +0.019836
        to_signed( -29436, 18),  -- [  37] b1 = -0.898315
        to_signed( -30167, 18),  -- [  38] b2 = -0.920624
        to_signed(  32036, 18),  -- [  39] b3 = +0.977661
        to_signed(  32768, 18),  -- [  40] b0 = +1.000000
        to_signed(    731, 18),  -- [  41] a0 = +0.022308
        to_signed(   2192, 18),  -- [  42] a1 = +0.066895
        to_signed(   2192, 18),  -- [  43] a2 = +0.066895
        to_signed(    731, 18),  -- [  44] a3 = +0.022308
        to_signed( -29115, 18),  -- [  45] b1 = -0.888519
        to_signed( -29845, 18),  -- [  46] b2 = -0.910797
        to_signed(  32038, 18),  -- [  47] b3 = +0.977722
        to_signed(  32768, 18),  -- [  48] b0 = +1.000000
        to_signed(    812, 18),  -- [  49] a0 = +0.024780
        to_signed(   2437, 18),  -- [  50] a1 = +0.074371
        to_signed(   2437, 18),  -- [  51] a2 = +0.074371
        to_signed(    812, 18),  -- [  52] a3 = +0.024780
        to_signed( -28791, 18),  -- [  53] b1 = -0.878632
        to_signed( -29519, 18),  -- [  54] b2 = -0.900848
        to_signed(  32040, 18),  -- [  55] b3 = +0.977783
        to_signed(  32768, 18),  -- [  56] b0 = +1.000000
        to_signed(    892, 18),  -- [  57] a0 = +0.027222
        to_signed(   2677, 18),  -- [  58] a1 = +0.081696
        to_signed(   2677, 18),  -- [  59] a2 = +0.081696
        to_signed(    892, 18),  -- [  60] a3 = +0.027222
        to_signed( -28473, 18),  -- [  61] b1 = -0.868927
        to_signed( -29199, 18),  -- [  62] b2 = -0.891083
        to_signed(  32042, 18),  -- [  63] b3 = +0.977844
        to_signed(  32768, 18),  -- [  64] b0 = +1.000000
        to_signed(    976, 18),  -- [  65] a0 = +0.029785
        to_signed(   2928, 18),  -- [  66] a1 = +0.089355
        to_signed(   2928, 18),  -- [  67] a2 = +0.089355
        to_signed(    976, 18),  -- [  68] a3 = +0.029785
        to_signed( -28140, 18),  -- [  69] b1 = -0.858765
        to_signed( -28865, 18),  -- [  70] b2 = -0.880890
        to_signed(  32044, 18),  -- [  71] b3 = +0.977905
        to_signed(  32768, 18),  -- [  72] b0 = +1.000000
        to_signed(   1055, 18),  -- [  73] a0 = +0.032196
        to_signed(   3165, 18),  -- [  74] a1 = +0.096588
        to_signed(   3165, 18),  -- [  75] a2 = +0.096588
        to_signed(   1055, 18),  -- [  76] a3 = +0.032196
        to_signed( -27826, 18),  -- [  77] b1 = -0.849182
        to_signed( -28548, 18),  -- [  78] b2 = -0.871216
        to_signed(  32045, 18),  -- [  79] b3 = +0.977936
        to_signed(  32768, 18),  -- [  80] b0 = +1.000000
        to_signed(   1135, 18),  -- [  81] a0 = +0.034637
        to_signed(   3404, 18),  -- [  82] a1 = +0.103882
        to_signed(   3404, 18),  -- [  83] a2 = +0.103882
        to_signed(   1135, 18),  -- [  84] a3 = +0.034637
        to_signed( -27508, 18),  -- [  85] b1 = -0.839478
        to_signed( -28229, 18),  -- [  86] b2 = -0.861481
        to_signed(  32047, 18),  -- [  87] b3 = +0.977997
        to_signed(  32768, 18),  -- [  88] b0 = +1.000000
        to_signed(   1213, 18),  -- [  89] a0 = +0.037018
        to_signed(   3639, 18),  -- [  90] a1 = +0.111053
        to_signed(   3639, 18),  -- [  91] a2 = +0.111053
        to_signed(   1213, 18),  -- [  92] a3 = +0.037018
        to_signed( -27197, 18),  -- [  93] b1 = -0.829987
        to_signed( -27916, 18),  -- [  94] b2 = -0.851929
        to_signed(  32049, 18),  -- [  95] b3 = +0.978058
        to_signed(  32768, 18),  -- [  96] b0 = +1.000000
        to_signed(   1295, 18),  -- [  97] a0 = +0.039520
        to_signed(   3885, 18),  -- [  98] a1 = +0.118561
        to_signed(   3885, 18),  -- [  99] a2 = +0.118561
        to_signed(   1295, 18),  -- [ 100] a3 = +0.039520
        to_signed( -26871, 18),  -- [ 101] b1 = -0.820038
        to_signed( -27588, 18),  -- [ 102] b2 = -0.841919
        to_signed(  32051, 18),  -- [ 103] b3 = +0.978119
        to_signed(  32768, 18),  -- [ 104] b0 = +1.000000
        to_signed(   1373, 18),  -- [ 105] a0 = +0.041901
        to_signed(   4118, 18),  -- [ 106] a1 = +0.125671
        to_signed(   4118, 18),  -- [ 107] a2 = +0.125671
        to_signed(   1373, 18),  -- [ 108] a3 = +0.041901
        to_signed( -26562, 18),  -- [ 109] b1 = -0.810608
        to_signed( -27278, 18),  -- [ 110] b2 = -0.832458
        to_signed(  32053, 18),  -- [ 111] b3 = +0.978180
        to_signed(  32768, 18),  -- [ 112] b0 = +1.000000
        to_signed(   1451, 18),  -- [ 113] a0 = +0.044281
        to_signed(   4352, 18),  -- [ 114] a1 = +0.132812
        to_signed(   4352, 18),  -- [ 115] a2 = +0.132812
        to_signed(   1451, 18),  -- [ 116] a3 = +0.044281
        to_signed( -26251, 18),  -- [ 117] b1 = -0.801117
        to_signed( -26965, 18),  -- [ 118] b2 = -0.822906
        to_signed(  32054, 18),  -- [ 119] b3 = +0.978210
        to_signed(  32768, 18),  -- [ 120] b0 = +1.000000
        to_signed(   1528, 18),  -- [ 121] a0 = +0.046631
        to_signed(   4583, 18),  -- [ 122] a1 = +0.139862
        to_signed(   4583, 18),  -- [ 123] a2 = +0.139862
        to_signed(   1528, 18),  -- [ 124] a3 = +0.046631
        to_signed( -25946, 18),  -- [ 125] b1 = -0.791809
        to_signed( -26658, 18),  -- [ 126] b2 = -0.813538
        to_signed(  32056, 18)   -- [ 127] b3 = +0.978271
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;