-- f4_rom.vhd
-- Votrax SC01-A: Fourth Formant (F4) Filter Coefficient ROM
--
-- Copyright (c) 2026 shufps
-- https://github.com/shufps/votrax-sc01a-vhdl
--
-- BSD 3-Clause License
--
-- Based on votrax.cpp (MAME), Copyright (c) Olivier Galibert
-- Auto-generated by gen_votrax_roms.cpp
--
-- Fixed filter (single operating point): 8 entries, s(2.15) 18-bit
-- addr[2:0] = coeff index: 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f4_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(2 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f4_rom is

    type rom_t is array(0 to 7) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(   2903, 18),  -- [   1] a0 = +0.088593
        to_signed(   8709, 18),  -- [   2] a1 = +0.265778
        to_signed(   8709, 18),  -- [   3] a2 = +0.265778
        to_signed(   2903, 18),  -- [   4] a3 = +0.088593
        to_signed( -20356, 18),  -- [   5] b1 = -0.621216
        to_signed( -21156, 18),  -- [   6] b2 = -0.645630
        to_signed(  31968, 18)   -- [   7] b3 = +0.975586
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;