-- Auto-generated by gen_votrax_roms.cpp
-- f4_rom: 8 entries x 18-bit s(2.15)
-- addr(2:0) = coeff_idx: 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity f4_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(2 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of f4_rom is

    type rom_t is array(0 to 7) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(   3085, 18),  -- [   1] a0 = +0.094147
        to_signed(   9254, 18),  -- [   2] a1 = +0.282410
        to_signed(   9254, 18),  -- [   3] a2 = +0.282410
        to_signed(   3085, 18),  -- [   4] a3 = +0.094147
        to_signed( -19607, 18),  -- [   5] b1 = -0.598358
        to_signed( -20429, 18),  -- [   6] b2 = -0.623444
        to_signed(  31946, 18)   -- [   7] b3 = +0.974915
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;
