-- fn_rom.vhd
-- Votrax SC01-A: Nasal Formant (FN) Filter Coefficient ROM
--
-- Copyright (c) 2026 shufps
-- https://github.com/shufps/votrax-sc01a-vhdl
--
-- BSD 3-Clause License
--
-- Based on votrax.cpp (MAME), Copyright (c) Olivier Galibert
-- Auto-generated by gen_votrax_roms.cpp
--
-- Fixed filter (single operating point): 8 entries, s(2.15) 18-bit
-- DC stabilization via pole displacement handled in iir_filter_slow
-- (DC_DRAIN generic). addr[2:0] = coeff index:
-- 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fn_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(2 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of fn_rom is

    type rom_t is array(0 to 7) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(   9890, 18),  -- [   1] a0 = +0.301827
        to_signed(      0, 18),  -- [   2] a1 = +0.000000
        to_signed(  -9890, 18),  -- [   3] a2 = -0.301827
        to_signed(      0, 18),  -- [   4] a3 = +0.000000
--      to_signed( -36284, 18),  -- [   5] b1 = -1.107293 !not stable in FP -> DC drift
        to_signed( -36250, 18),  -- [   5] b1 = -1.106262
		to_signed(   3516, 18),  -- [   6] b2 = +0.107293
        to_signed(      0, 18)   -- [   7] b3 = +0.000000
    );


begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;