-- Auto-generated by gen_votrax_roms.cpp
-- fn_rom: 8 entries x 18-bit s(2.15)
-- addr(2:0) = coeff_idx: 0=b0 1=a0 2=a1 3=a2 4=a3 5=b1 6=b2 7=b3
-- Synchronous read: 1-cycle latency, infers as BRAM

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fn_rom is
    port (
        clk  : in  std_logic;
        addr : in  unsigned(2 downto 0);
        data : out signed(17 downto 0)
    );
end entity;

architecture rtl of fn_rom is

    type rom_t is array(0 to 7) of signed(17 downto 0);
    constant ROM : rom_t := (
        to_signed(  32768, 18),  -- [   0] b0 = +1.000000
        to_signed(   3717, 18),  -- [   1] a0 = +0.113434
        to_signed(      0, 18),  -- [   2] a1 = +0.000000
        to_signed(  -3717, 18),  -- [   3] a2 = -0.113434
        to_signed(      0, 18),  -- [   4] a3 = +0.000000
--        to_signed( -54543, 18),  -- [   5] b1 = -1.664520 - with fixed point instabil -> DC drift
        to_signed( -54500, 18),  -- [   5] b1 = -1.663208
        to_signed(  21775, 18),  -- [   6] b2 = +0.664520
        to_signed(      0, 18)   -- [   7] b3 = +0.000000
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            data <= ROM(to_integer(addr));
        end if;
    end process;

end architecture;
