-- Auto-generated by votrax_dump_to_vhdl.py
-- Votrax SC01A testbench input vectors
-- DO NOT EDIT - regenerate from votrax_input.txt

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package votrax_tb_vectors is

    -- Event types
    constant EV_RESET      : integer := 0;
    constant EV_CLOCK      : integer := 1;
    constant EV_PHONE      : integer := 2;  -- data(5:0)=phone, data(7:6)=inflection
    constant EV_INFLECTION : integer := 3;  -- data(1:0)=inflection

    type input_event_t is record
        ts_us  : integer;  -- timestamp in microseconds
        event  : integer;  -- event type (EV_*)
        data   : integer;  -- event data
    end record;

    constant N_EVENTS : integer := 246;

    type input_vec_array is array(0 to N_EVENTS-1) of input_event_t;

    constant INPUT_VECTORS : input_vec_array := (
        (ts_us=>         0, event=>0, data=>         0),  -- RESET
        (ts_us=>       120, event=>1, data=>    950000),  -- CLOCK freq=950000Hz
        (ts_us=>       135, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>       135, event=>2, data=>       254),  -- PHONE phone=0x3E inflection=3
        (ts_us=>    141544, event=>2, data=>       219),  -- PHONE phone=0x1B inflection=3
        (ts_us=>    198069, event=>2, data=>       192),  -- PHONE phone=0x00 inflection=3
        (ts_us=>    244892, event=>2, data=>       216),  -- PHONE phone=0x18 inflection=3
        (ts_us=>    325669, event=>2, data=>       215),  -- PHONE phone=0x17 inflection=3
        (ts_us=>    467080, event=>2, data=>       237),  -- PHONE phone=0x2D inflection=3
        (ts_us=>    530881, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    568003, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    605126, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    642249, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    679371, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    716495, event=>2, data=>       213),  -- PHONE phone=0x15 inflection=3
        (ts_us=>    828802, event=>2, data=>       192),  -- PHONE phone=0x00 inflection=3
        (ts_us=>    875625, event=>2, data=>       201),  -- PHONE phone=0x09 inflection=3
        (ts_us=>    920024, event=>2, data=>       233),  -- PHONE phone=0x29 inflection=3
        (ts_us=>   1000802, event=>2, data=>       204),  -- PHONE phone=0x0C inflection=3
        (ts_us=>   1081580, event=>2, data=>       234),  -- PHONE phone=0x2A inflection=3
        (ts_us=>   1138105, event=>2, data=>       250),  -- PHONE phone=0x3A inflection=3
        (ts_us=>   1250412, event=>2, data=>       202),  -- PHONE phone=0x0A inflection=3
        (ts_us=>   1314211, event=>2, data=>       205),  -- PHONE phone=0x0D inflection=3
        (ts_us=>   1378010, event=>2, data=>       222),  -- PHONE phone=0x1E inflection=3
        (ts_us=>   1422409, event=>2, data=>       228),  -- PHONE phone=0x24 inflection=3
        (ts_us=>   1607474, event=>2, data=>       205),  -- PHONE phone=0x0D inflection=3
        (ts_us=>   1671273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   1871273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   2071273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
--
        (ts_us=>   2271273, event=>2, data=>       245),  -- PHONE phone=0x35 inflection=3
        (ts_us=>   2272410, event=>1, data=>    955500),  -- CLOCK freq=955500Hz
        (ts_us=>   2275373, event=>1, data=>    961000),  -- CLOCK freq=961000Hz
        (ts_us=>   2278223, event=>1, data=>    966500),  -- CLOCK freq=966500Hz
        (ts_us=>   2281186, event=>1, data=>    972000),  -- CLOCK freq=972000Hz
        (ts_us=>   2284036, event=>1, data=>    977500),  -- CLOCK freq=977500Hz
        (ts_us=>   2287000, event=>1, data=>    983000),  -- CLOCK freq=983000Hz
        (ts_us=>   2289963, event=>1, data=>    988500),  -- CLOCK freq=988500Hz
        (ts_us=>   2292813, event=>1, data=>    994000),  -- CLOCK freq=994000Hz
        (ts_us=>   2295776, event=>1, data=>    999500),  -- CLOCK freq=999500Hz
        (ts_us=>   2298626, event=>1, data=>   1005000),  -- CLOCK freq=1005000Hz
        (ts_us=>   2301589, event=>1, data=>   1010500),  -- CLOCK freq=1010500Hz
        (ts_us=>   2304553, event=>1, data=>   1016000),  -- CLOCK freq=1016000Hz
        (ts_us=>   2307402, event=>1, data=>   1021500),  -- CLOCK freq=1021500Hz
        (ts_us=>   2310366, event=>1, data=>   1027000),  -- CLOCK freq=1027000Hz
        (ts_us=>   2313215, event=>1, data=>   1032500),  -- CLOCK freq=1032500Hz
        (ts_us=>   2316179, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   2319142, event=>1, data=>   1043500),  -- CLOCK freq=1043500Hz
        (ts_us=>   2321992, event=>1, data=>   1049000),  -- CLOCK freq=1049000Hz
        (ts_us=>   2324955, event=>1, data=>   1054500),  -- CLOCK freq=1054500Hz
        (ts_us=>   2327805, event=>1, data=>   1060000),  -- CLOCK freq=1060000Hz
        (ts_us=>   2330768, event=>1, data=>   1065500),  -- CLOCK freq=1065500Hz
        (ts_us=>   2333732, event=>1, data=>   1071000),  -- CLOCK freq=1071000Hz
        (ts_us=>   2336581, event=>1, data=>   1076500),  -- CLOCK freq=1076500Hz
        (ts_us=>   2339545, event=>1, data=>   1082000),  -- CLOCK freq=1082000Hz
        (ts_us=>   2342394, event=>1, data=>   1087500),  -- CLOCK freq=1087500Hz
        (ts_us=>   2345358, event=>1, data=>   1093000),  -- CLOCK freq=1093000Hz
        (ts_us=>   2348321, event=>1, data=>   1098500),  -- CLOCK freq=1098500Hz
        (ts_us=>   2351171, event=>1, data=>   1104000),  -- CLOCK freq=1104000Hz
        (ts_us=>   2354134, event=>1, data=>   1109500),  -- CLOCK freq=1109500Hz
        (ts_us=>   2356984, event=>1, data=>   1115000),  -- CLOCK freq=1115000Hz
        (ts_us=>   2359947, event=>1, data=>   1120500),  -- CLOCK freq=1120500Hz
        (ts_us=>   2362911, event=>1, data=>   1126000),  -- CLOCK freq=1126000Hz
        (ts_us=>   2365760, event=>1, data=>   1131500),  -- CLOCK freq=1131500Hz
        (ts_us=>   2368724, event=>1, data=>   1137000),  -- CLOCK freq=1137000Hz
        (ts_us=>   2371573, event=>1, data=>   1142500),  -- CLOCK freq=1142500Hz
        (ts_us=>   2374537, event=>1, data=>   1148000),  -- CLOCK freq=1148000Hz
        (ts_us=>   2377500, event=>1, data=>   1153500),  -- CLOCK freq=1153500Hz
        (ts_us=>   2380350, event=>1, data=>   1159000),  -- CLOCK freq=1159000Hz
        (ts_us=>   2383313, event=>1, data=>   1164500),  -- CLOCK freq=1164500Hz
        (ts_us=>   2386163, event=>1, data=>   1170000),  -- CLOCK freq=1170000Hz
        (ts_us=>   2389126, event=>1, data=>   1175500),  -- CLOCK freq=1175500Hz
        (ts_us=>   2392090, event=>1, data=>   1181000),  -- CLOCK freq=1181000Hz
        (ts_us=>   2394940, event=>1, data=>   1186500),  -- CLOCK freq=1186500Hz
        (ts_us=>   2397903, event=>1, data=>   1192000),  -- CLOCK freq=1192000Hz
        (ts_us=>   2400753, event=>1, data=>   1197500),  -- CLOCK freq=1197500Hz
        (ts_us=>   2403716, event=>1, data=>   1203000),  -- CLOCK freq=1203000Hz
        (ts_us=>   2406680, event=>1, data=>   1208500),  -- CLOCK freq=1208500Hz
        (ts_us=>   2409529, event=>1, data=>   1214000),  -- CLOCK freq=1214000Hz
        (ts_us=>   2412493, event=>1, data=>   1219500),  -- CLOCK freq=1219500Hz
        (ts_us=>   2415342, event=>1, data=>   1225000),  -- CLOCK freq=1225000Hz
        (ts_us=>   2418306, event=>1, data=>   1230500),  -- CLOCK freq=1230500Hz
        (ts_us=>   2421269, event=>1, data=>   1236000),  -- CLOCK freq=1236000Hz
        (ts_us=>   2424119, event=>1, data=>   1241500),  -- CLOCK freq=1241500Hz
        (ts_us=>   2427082, event=>1, data=>   1247000),  -- CLOCK freq=1247000Hz
        (ts_us=>   2429932, event=>1, data=>   1252500),  -- CLOCK freq=1252500Hz
        (ts_us=>   2432895, event=>1, data=>   1258000),  -- CLOCK freq=1258000Hz
        (ts_us=>   2435859, event=>1, data=>   1263500),  -- CLOCK freq=1263500Hz
        (ts_us=>   2438708, event=>1, data=>   1269000),  -- CLOCK freq=1269000Hz
        (ts_us=>   2441672, event=>1, data=>   1274500),  -- CLOCK freq=1274500Hz
        (ts_us=>   2444521, event=>1, data=>   1280000),  -- CLOCK freq=1280000Hz
        (ts_us=>   2447485, event=>1, data=>   1285500),  -- CLOCK freq=1285500Hz
        (ts_us=>   2450448, event=>1, data=>   1291000),  -- CLOCK freq=1291000Hz
        (ts_us=>   2453298, event=>1, data=>   1296500),  -- CLOCK freq=1296500Hz
        (ts_us=>   2456261, event=>1, data=>   1302000),  -- CLOCK freq=1302000Hz
        (ts_us=>   2459111, event=>1, data=>   1307500),  -- CLOCK freq=1307500Hz
        (ts_us=>   2462074, event=>1, data=>   1313000),  -- CLOCK freq=1313000Hz
        (ts_us=>   2465038, event=>1, data=>   1318500),  -- CLOCK freq=1318500Hz
        (ts_us=>   2467887, event=>1, data=>   1324000),  -- CLOCK freq=1324000Hz
        (ts_us=>   2470851, event=>1, data=>   1329500),  -- CLOCK freq=1329500Hz
        (ts_us=>   2473700, event=>1, data=>   1335000),  -- CLOCK freq=1335000Hz
        (ts_us=>   2476664, event=>1, data=>   1340500),  -- CLOCK freq=1340500Hz
        (ts_us=>   2479627, event=>1, data=>   1346000),  -- CLOCK freq=1346000Hz
        (ts_us=>   2482477, event=>1, data=>   1351500),  -- CLOCK freq=1351500Hz
        (ts_us=>   2485440, event=>1, data=>   1357000),  -- CLOCK freq=1357000Hz
        (ts_us=>   2488290, event=>1, data=>   1362500),  -- CLOCK freq=1362500Hz
        (ts_us=>   2491253, event=>1, data=>   1368000),  -- CLOCK freq=1368000Hz
        (ts_us=>   2494217, event=>1, data=>   1373500),  -- CLOCK freq=1373500Hz
        (ts_us=>   2497066, event=>1, data=>   1379000),  -- CLOCK freq=1379000Hz
        (ts_us=>   2500030, event=>1, data=>   1384500),  -- CLOCK freq=1384500Hz
        (ts_us=>   2502880, event=>1, data=>   1390000),  -- CLOCK freq=1390000Hz
        (ts_us=>   2505843, event=>1, data=>   1395500),  -- CLOCK freq=1395500Hz
        (ts_us=>   2508807, event=>1, data=>   1401000),  -- CLOCK freq=1401000Hz
        (ts_us=>   2511656, event=>1, data=>   1406500),  -- CLOCK freq=1406500Hz
        (ts_us=>   2514620, event=>1, data=>   1412000),  -- CLOCK freq=1412000Hz
        (ts_us=>   2517469, event=>1, data=>   1417500),  -- CLOCK freq=1417500Hz
        (ts_us=>   2520433, event=>1, data=>   1423000),  -- CLOCK freq=1423000Hz
        (ts_us=>   2523396, event=>1, data=>   1428500),  -- CLOCK freq=1428500Hz
        (ts_us=>   2526246, event=>1, data=>   1434000),  -- CLOCK freq=1434000Hz
        (ts_us=>   2529209, event=>1, data=>   1439500),  -- CLOCK freq=1439500Hz
        (ts_us=>   2532059, event=>1, data=>   1445000),  -- CLOCK freq=1445000Hz
        (ts_us=>   2535022, event=>1, data=>   1450500),  -- CLOCK freq=1450500Hz
        (ts_us=>   2537986, event=>1, data=>   1456000),  -- CLOCK freq=1456000Hz
        (ts_us=>   2540835, event=>1, data=>   1461500),  -- CLOCK freq=1461500Hz
        (ts_us=>   2543799, event=>1, data=>   1467000),  -- CLOCK freq=1467000Hz
        (ts_us=>   2546648, event=>1, data=>   1472500),  -- CLOCK freq=1472500Hz
        (ts_us=>   2546771, event=>1, data=>   1467000),  -- CLOCK freq=1467000Hz
        (ts_us=>   2556460, event=>1, data=>   1461500),  -- CLOCK freq=1461500Hz
        (ts_us=>   2566148, event=>1, data=>   1456000),  -- CLOCK freq=1456000Hz
        (ts_us=>   2575950, event=>1, data=>   1450500),  -- CLOCK freq=1450500Hz
        (ts_us=>   2585639, event=>1, data=>   1445000),  -- CLOCK freq=1445000Hz
        (ts_us=>   2595327, event=>1, data=>   1439500),  -- CLOCK freq=1439500Hz
        (ts_us=>   2605129, event=>1, data=>   1434000),  -- CLOCK freq=1434000Hz
        (ts_us=>   2614818, event=>1, data=>   1428500),  -- CLOCK freq=1428500Hz
        (ts_us=>   2624506, event=>1, data=>   1423000),  -- CLOCK freq=1423000Hz
        (ts_us=>   2634309, event=>1, data=>   1417500),  -- CLOCK freq=1417500Hz
        (ts_us=>   2643997, event=>1, data=>   1412000),  -- CLOCK freq=1412000Hz
        (ts_us=>   2653685, event=>1, data=>   1406500),  -- CLOCK freq=1406500Hz
        (ts_us=>   2663488, event=>1, data=>   1401000),  -- CLOCK freq=1401000Hz
        (ts_us=>   2673176, event=>1, data=>   1395500),  -- CLOCK freq=1395500Hz
        (ts_us=>   2682864, event=>1, data=>   1390000),  -- CLOCK freq=1390000Hz
        (ts_us=>   2692667, event=>1, data=>   1384500),  -- CLOCK freq=1384500Hz
        (ts_us=>   2702355, event=>1, data=>   1379000),  -- CLOCK freq=1379000Hz
        (ts_us=>   2712044, event=>1, data=>   1373500),  -- CLOCK freq=1373500Hz
        (ts_us=>   2721846, event=>1, data=>   1368000),  -- CLOCK freq=1368000Hz
        (ts_us=>   2731534, event=>1, data=>   1362500),  -- CLOCK freq=1362500Hz
        (ts_us=>   2741223, event=>1, data=>   1357000),  -- CLOCK freq=1357000Hz
        (ts_us=>   2751025, event=>1, data=>   1351500),  -- CLOCK freq=1351500Hz
        (ts_us=>   2760713, event=>1, data=>   1346000),  -- CLOCK freq=1346000Hz
        (ts_us=>   2770402, event=>1, data=>   1340500),  -- CLOCK freq=1340500Hz
        (ts_us=>   2780204, event=>1, data=>   1335000),  -- CLOCK freq=1335000Hz
        (ts_us=>   2789893, event=>1, data=>   1329500),  -- CLOCK freq=1329500Hz
        (ts_us=>   2799581, event=>1, data=>   1324000),  -- CLOCK freq=1324000Hz
        (ts_us=>   2809383, event=>1, data=>   1318500),  -- CLOCK freq=1318500Hz
        (ts_us=>   2819072, event=>1, data=>   1313000),  -- CLOCK freq=1313000Hz
        (ts_us=>   2828760, event=>1, data=>   1307500),  -- CLOCK freq=1307500Hz
        (ts_us=>   2838563, event=>1, data=>   1302000),  -- CLOCK freq=1302000Hz
        (ts_us=>   2848251, event=>1, data=>   1296500),  -- CLOCK freq=1296500Hz
        (ts_us=>   2857939, event=>1, data=>   1291000),  -- CLOCK freq=1291000Hz
        (ts_us=>   2867742, event=>1, data=>   1285500),  -- CLOCK freq=1285500Hz
        (ts_us=>   2877430, event=>1, data=>   1280000),  -- CLOCK freq=1280000Hz
        (ts_us=>   2887118, event=>1, data=>   1274500),  -- CLOCK freq=1274500Hz
        (ts_us=>   2896921, event=>1, data=>   1269000),  -- CLOCK freq=1269000Hz
        (ts_us=>   2906609, event=>1, data=>   1263500),  -- CLOCK freq=1263500Hz
        (ts_us=>   2916298, event=>1, data=>   1258000),  -- CLOCK freq=1258000Hz
        (ts_us=>   2926100, event=>1, data=>   1252500),  -- CLOCK freq=1252500Hz
        (ts_us=>   2935788, event=>1, data=>   1247000),  -- CLOCK freq=1247000Hz
        (ts_us=>   2945477, event=>1, data=>   1241500),  -- CLOCK freq=1241500Hz
        (ts_us=>   2955279, event=>1, data=>   1236000),  -- CLOCK freq=1236000Hz
        (ts_us=>   2964967, event=>1, data=>   1230500),  -- CLOCK freq=1230500Hz
        (ts_us=>   2974656, event=>1, data=>   1225000),  -- CLOCK freq=1225000Hz
        (ts_us=>   2984458, event=>1, data=>   1219500),  -- CLOCK freq=1219500Hz
        (ts_us=>   2994147, event=>1, data=>   1214000),  -- CLOCK freq=1214000Hz
        (ts_us=>   3003835, event=>1, data=>   1208500),  -- CLOCK freq=1208500Hz
        (ts_us=>   3013637, event=>1, data=>   1203000),  -- CLOCK freq=1203000Hz
        (ts_us=>   3023326, event=>1, data=>   1197500),  -- CLOCK freq=1197500Hz
        (ts_us=>   3033014, event=>1, data=>   1192000),  -- CLOCK freq=1192000Hz
        (ts_us=>   3042816, event=>1, data=>   1186500),  -- CLOCK freq=1186500Hz
        (ts_us=>   3052505, event=>1, data=>   1181000),  -- CLOCK freq=1181000Hz
        (ts_us=>   3062193, event=>1, data=>   1175500),  -- CLOCK freq=1175500Hz
        (ts_us=>   3071996, event=>1, data=>   1170000),  -- CLOCK freq=1170000Hz
        (ts_us=>   3081684, event=>1, data=>   1164500),  -- CLOCK freq=1164500Hz
        (ts_us=>   3091372, event=>1, data=>   1159000),  -- CLOCK freq=1159000Hz
        (ts_us=>   3101175, event=>1, data=>   1153500),  -- CLOCK freq=1153500Hz
        (ts_us=>   3110863, event=>1, data=>   1148000),  -- CLOCK freq=1148000Hz
        (ts_us=>   3120551, event=>1, data=>   1142500),  -- CLOCK freq=1142500Hz
        (ts_us=>   3130354, event=>1, data=>   1137000),  -- CLOCK freq=1137000Hz
        (ts_us=>   3140042, event=>1, data=>   1131500),  -- CLOCK freq=1131500Hz
        (ts_us=>   3149731, event=>1, data=>   1126000),  -- CLOCK freq=1126000Hz
        (ts_us=>   3159533, event=>1, data=>   1120500),  -- CLOCK freq=1120500Hz
        (ts_us=>   3169221, event=>1, data=>   1115000),  -- CLOCK freq=1115000Hz
        (ts_us=>   3178910, event=>1, data=>   1109500),  -- CLOCK freq=1109500Hz
        (ts_us=>   3188712, event=>1, data=>   1104000),  -- CLOCK freq=1104000Hz
        (ts_us=>   3198401, event=>1, data=>   1098500),  -- CLOCK freq=1098500Hz
        (ts_us=>   3208089, event=>1, data=>   1093000),  -- CLOCK freq=1093000Hz
        (ts_us=>   3217891, event=>1, data=>   1087500),  -- CLOCK freq=1087500Hz
        (ts_us=>   3227580, event=>1, data=>   1082000),  -- CLOCK freq=1082000Hz
        (ts_us=>   3237268, event=>1, data=>   1076500),  -- CLOCK freq=1076500Hz
        (ts_us=>   3247070, event=>1, data=>   1071000),  -- CLOCK freq=1071000Hz
        (ts_us=>   3256759, event=>1, data=>   1065500),  -- CLOCK freq=1065500Hz
        (ts_us=>   3266447, event=>1, data=>   1060000),  -- CLOCK freq=1060000Hz
        (ts_us=>   3276250, event=>1, data=>   1054500),  -- CLOCK freq=1054500Hz
        (ts_us=>   3285938, event=>1, data=>   1049000),  -- CLOCK freq=1049000Hz
        (ts_us=>   3295626, event=>1, data=>   1043500),  -- CLOCK freq=1043500Hz
        (ts_us=>   3305429, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   3315117, event=>1, data=>   1032500),  -- CLOCK freq=1032500Hz
        (ts_us=>   3324805, event=>1, data=>   1027000),  -- CLOCK freq=1027000Hz
        (ts_us=>   3334608, event=>1, data=>   1021500),  -- CLOCK freq=1021500Hz
        (ts_us=>   3344296, event=>1, data=>   1016000),  -- CLOCK freq=1016000Hz
        (ts_us=>   3353985, event=>1, data=>   1010500),  -- CLOCK freq=1010500Hz
        (ts_us=>   3363787, event=>1, data=>   1005000),  -- CLOCK freq=1005000Hz
        (ts_us=>   3373475, event=>1, data=>    999500),  -- CLOCK freq=999500Hz
        (ts_us=>   3383164, event=>1, data=>    994000),  -- CLOCK freq=994000Hz
        (ts_us=>   3392966, event=>1, data=>    988500),  -- CLOCK freq=988500Hz
        (ts_us=>   3402654, event=>1, data=>    983000),  -- CLOCK freq=983000Hz
        (ts_us=>   3412343, event=>1, data=>    977500),  -- CLOCK freq=977500Hz
        (ts_us=>   3422145, event=>1, data=>    972000),  -- CLOCK freq=972000Hz
        (ts_us=>   3431834, event=>1, data=>    966500),  -- CLOCK freq=966500Hz
        (ts_us=>   3441522, event=>1, data=>    961000),  -- CLOCK freq=961000Hz
        (ts_us=>   3451324, event=>1, data=>    955500),  -- CLOCK freq=955500Hz
        (ts_us=>   3461013, event=>1, data=>    950000),  -- CLOCK freq=950000Hz
        (ts_us=>   3470701, event=>1, data=>    944500),  -- CLOCK freq=944500Hz
        (ts_us=>   3476056, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   3676056, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   3876056, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   4076056, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   4076070, event=>2, data=>       193),  -- PHONE phone=0x01 inflection=3
        (ts_us=>   4127842, event=>3, data=>         0),  -- INFLECTION inflection=0
        (ts_us=>   4127842, event=>2, data=>        44),  -- PHONE phone=0x2C inflection=0
        (ts_us=>   4257300, event=>2, data=>        54),  -- PHONE phone=0x36 inflection=0
        (ts_us=>   4300192, event=>3, data=>         2),  -- INFLECTION inflection=2
        (ts_us=>   4300192, event=>2, data=>       187),  -- PHONE phone=0x3B inflection=2
        (ts_us=>   4429650, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   4429650, event=>2, data=>       253),  -- PHONE phone=0x3D inflection=3
        (ts_us=>   4599063, event=>3, data=>         1),  -- INFLECTION inflection=1
        (ts_us=>   4599063, event=>2, data=>        94),  -- PHONE phone=0x1E inflection=1
        (ts_us=>   4639736, event=>3, data=>         0),  -- INFLECTION inflection=0
        (ts_us=>   4639736, event=>2, data=>        15),  -- PHONE phone=0x0F inflection=0
        (ts_us=>   4691507, event=>2, data=>        39),  -- PHONE phone=0x27 inflection=0
        (ts_us=>   4808587, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   4808587, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   4842600, event=>3, data=>         2),  -- INFLECTION inflection=2
        (ts_us=>   4842600, event=>2, data=>       179),  -- PHONE phone=0x33 inflection=2
        (ts_us=>   4972058, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   4972058, event=>2, data=>       249),  -- PHONE phone=0x39 inflection=3
        (ts_us=>   5023829, event=>2, data=>       220),  -- PHONE phone=0x1C inflection=3
        (ts_us=>   5075554, event=>2, data=>       255)   -- PHONE phone=0x3F inflection=3
    );

end package votrax_tb_vectors;